# Generated by Django 5.2.15 on 2026-08-01 04:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_instrument_and_more"),
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account_type", "income")),
                fields=("owner", "name"),
                name="one_income_account_per_name",
            ),
        ),
    ]
