# Generated by Django 5.2.15 on 2026-08-05 03:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_one_income_account_per_name"),
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="account",
            name="position_account_is_an_asset",
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("instrument__isnull", True),
                    ("account_type__in", ["asset", "equity"]),
                    _connector="OR",
                ),
                name="instrument_account_is_an_asset_or_equity",
            ),
        ),
    ]
