# Generated by Django 5.2.15 on 2026-08-01 04:47

from decimal import Decimal

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("sector", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("initial_price", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "drift",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0800"), max_digits=6),
                ),
                (
                    "volatility",
                    models.DecimalField(decimal_places=4, default=Decimal("0.2500"), max_digits=6),
                ),
                (
                    "last_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("last_tick_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["symbol"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("initial_price__gt", 0)),
                        name="instrument_initial_price_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("volatility__gte", 0)),
                        name="instrument_volatility_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceTick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=4, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticks",
                        to="markets.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "-created_at"], name="tick_instrument_created_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gt", 0)), name="price_tick_price_positive"
                    )
                ],
            },
        ),
    ]
