# Generated by Django 5.2.15 on 2026-08-03 03:11

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models

import statements.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_account_one_income_account_per_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("cash", "Cash account"), ("brokerage", "Brokerage")], max_length=9
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("opening_balance", models.DecimalField(decimal_places=4, max_digits=20)),
                ("closing_balance", models.DecimalField(decimal_places=4, max_digits=20)),
                ("line_count", models.PositiveIntegerField(default=0)),
                ("file", models.FileField(upload_to=statements.models.statement_upload_to)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statements",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "kind"],
                "indexes": [
                    models.Index(fields=["user", "-period_start"], name="statement_user_period_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "cash")),
                        fields=("account", "period_start"),
                        name="one_cash_statement_per_account_month",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "brokerage")),
                        fields=("user", "period_start"),
                        name="one_brokerage_statement_per_user_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("account__isnull", False), ("kind", "cash")),
                            models.Q(("account__isnull", True), ("kind", "brokerage")),
                            _connector="OR",
                        ),
                        name="statement_account_iff_cash",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_end__gte", models.F("period_start"))),
                        name="statement_period_ordered",
                    ),
                ],
            },
        ),
    ]
