/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your money accounts, with derived balances
         * @description List and retrieve the requesting user's money accounts, each with its derived balance.
         *
         *     Position accounts are deliberately excluded (ADR-0016). Their balance is a *cost basis* in USD,
         *     not spendable cash, and listing the two side by side under one ``balance`` field would invite
         *     exactly that misreading — by a client, and by whoever writes the next feature. Holdings have
         *     their own endpoint, where the share count is shown alongside the basis that explains it.
         *
         *     ``spendable()`` rather than ``cash()`` since Week 8: the latter also admitted the equity and
         *     income accounts that fund and absorb a user's own money, which turned this list into a menu of
         *     bookkeeping rows — and, because the transfer endpoint took its source from the same scope, into
         *     a way to spend them.
         */
        get: operations["accounts_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One account, with its full account number
         * @description List and retrieve the requesting user's money accounts, each with its derived balance.
         *
         *     Position accounts are deliberately excluded (ADR-0016). Their balance is a *cost basis* in USD,
         *     not spendable cash, and listing the two side by side under one ``balance`` field would invite
         *     exactly that misreading — by a client, and by whoever writes the next feature. Holdings have
         *     their own endpoint, where the share count is shown alongside the basis that explains it.
         *
         *     ``spendable()`` rather than ``cash()`` since Week 8: the latter also admitted the equity and
         *     income accounts that fund and absorb a user's own money, which turned this list into a menu of
         *     bookkeeping rows — and, because the transfer endpoint took its source from the same scope, into
         *     a way to spend them.
         */
        get: operations["accounts_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description An owned account's journal lines, newest first, cursor-paginated.
         *
         *     Ordered by ``-created_at`` (the pagination default), which is exactly the
         *     ``(account, created_at)`` composite index built in Week 2.
         */
        get: operations["accounts_transactions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Blacklists the refresh token **and** revokes its session, so every access token from that login stops working immediately rather than living out its remaining lifetime.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The requesting user's own profile — never anyone else's, by construction. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an enrolled MFA device
         * @description Activate an enrolled device. Until this succeeds, MFA is not enforced at login.
         */
        post: operations["auth_mfa_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/disable/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable MFA
         * @description Every session is revoked on the way out. Changing an account's authentication requirements is exactly when any session an attacker holds should stop working.
         */
        post: operations["auth_mfa_disable_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enroll/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin MFA enrollment
         * @description The only response that carries the TOTP secret. It is stored encrypted at rest (ADR-0027); this is the one moment it crosses the wire, because the user has to scan it. Enrollment does not enforce MFA — confirmation does.
         */
        post: operations["auth_mfa_enroll_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Returns the new user, never a token — registration is not a login.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Password step. Returns a token pair, or an MFA challenge (ADR-0012).
         *
         *     The serializer comes from ``SIMPLE_JWT["TOKEN_OBTAIN_SERIALIZER"]``; this subclass exists only
         *     to carry the throttle scope. ``TokenViewBase`` already opts out of authentication and the
         *     ``IsAuthenticated`` default.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/mfa/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Second step: spend the pre-auth token plus a TOTP code for a real token pair. */
        post: operations["auth_token_mfa_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Rotate a refresh token. Reuse of a rotated token revokes the whole family (ADR-0013). */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Liveness probe. Checks nothing, on purpose.
         *
         *     If this view runs at all, the process is alive and serving — which is the entire question. It
         *     deliberately does not touch Postgres or Redis: a liveness probe that fails on a dependency
         *     outage asks the supervisor to restart a process that is working fine, turning a recoverable
         *     outage into a restart storm on top of one. Readiness is where dependencies belong.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/holdings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your holdings
         * @description ``GET /api/v1/holdings/`` — every instrument the requester holds.
         *
         *     All of the arithmetic lives in :func:`trading.portfolio.holdings_for`, which the portfolio
         *     endpoint and the brokerage statement also call. Two implementations of "what is this position
         *     worth" is exactly the drift ADR-0016 built derived holdings to avoid.
         */
        get: operations["holdings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List and retrieve tradeable instruments, looked up by symbol.
         *
         *     The symbol is the lookup key rather than the UUID PK: it is unique, stable, and the thing a
         *     human actually types. ADR-0005's non-enumerable-identifier reasoning does not apply here —
         *     instruments are public reference data, and the whole list is one request away by design.
         */
        get: operations["instruments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{symbol}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List and retrieve tradeable instruments, looked up by symbol.
         *
         *     The symbol is the lookup key rather than the UUID PK: it is unique, stable, and the thing a
         *     human actually types. ADR-0005's non-enumerable-identifier reasoning does not apply here —
         *     instruments are public reference data, and the whole list is one request away by design.
         */
        get: operations["instruments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{symbol}/prices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/v1/instruments/{symbol}/prices/`` — tick history, newest first. */
        get: operations["instruments_prices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List your orders, newest first
         * @description Cursor-paginated, newest first.
         *
         *     Unbounded until Week 7: this returned every order the user had ever placed, in one response,
         *     growing forever. It was the endpoint most likely to be the first to time out.
         */
        get: operations["orders_list"];
        put?: never;
        /**
         * Place an order
         * @description A market order returns 201 already `filled`; a limit order returns 201 `open` and rests until the market crosses it. Both are 201 — `status`, not the HTTP code, is what says whether money moved.
         */
        post: operations["orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve one of your orders
         * @description ``GET /api/v1/orders/{id}/`` — one of the requester's own orders.
         */
        get: operations["orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a resting order
         * @description ``POST /api/v1/orders/{id}/cancel/`` — withdraw a resting order.
         */
        post: operations["orders_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cash, holdings and total value
         * @description ``GET /api/v1/portfolio/`` — cash, holdings, and what the difference is worth (ADR-0020).
         *
         *     Every figure is derived from ledger rows at request time; the endpoint adds no state of its own
         *     and its correctness is therefore a property of the postings, not of anything it stores.
         */
        get: operations["portfolio_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description 503 with a per-dependency breakdown when something it needs is unreachable.
         */
        get: operations["ready_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description ``GET /api/v1/statements/`` — the requester's statements, newest first. */
        get: operations["statements_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statements/{id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a statement PDF
         * @description Owner-scoped: another user's statement is a 404, not a 403, so the endpoint does not confirm that it exists. MEDIA_URL is deliberately unrouted, making this the only path to a generated file (ADR-0021).
         */
        get: operations["statements_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/transfers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move money between accounts
         * @description 201 when the transfer posted, **200** when an idempotency key replayed one that had already posted — the status is how a client tells "I made this happen" from "this had already happened". A key reused for a *different* request is 409.
         */
        post: operations["transfers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description An account with its derived balance.
         *
         *     ``balance`` is not a model field: it comes from the queryset annotation in ``AccountViewSet``,
         *     so a list of N accounts still costs one query. Declared explicitly (rather than left to
         *     ``ModelSerializer`` inference) so the decimal places match the storage contract of ADR-0009 —
         *     and so it serializes as the string ``"150.0000"``, never a float.
         */
        Account: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly number: string;
            readonly account_type: components["schemas"]["AccountTypeEnum"];
            readonly currency: string;
            /** Format: decimal */
            readonly balance: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description One account, with its account number in full.
         *
         *     The only place the number is decrypted. Retrieving a single owned account is the one request
         *     where a customer genuinely needs the digits — to quote them to somebody — and confining the
         *     decryption to it means a leak of the list endpoint leaks four digits rather than all ten.
         */
        AccountDetail: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly number: string;
            readonly account_type: components["schemas"]["AccountTypeEnum"];
            readonly currency: string;
            /** Format: decimal */
            readonly balance: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `asset` - Asset
         *     * `liability` - Liability
         *     * `equity` - Equity
         *     * `income` - Income
         *     * `expense` - Expense
         * @enum {string}
         */
        AccountTypeEnum: "asset" | "liability" | "equity" | "income" | "expense";
        ErrorBody: {
            /** @description Machine-readable code clients branch on. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description The ADR-0006 error envelope, as one reusable schema component.
         *
         *     One class rather than an ``inline_serializer`` per call site, and the reason is concrete:
         *     inline serializers mint a new class each time, so fifteen call sites produce fifteen components
         *     with the same name and spectacular resolves the collision by guessing. An error shape documented
         *     fifteen slightly different ways is a shape no client can rely on.
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * @description One position: how much is held, what it cost, and what it is worth now.
         *
         *     Every field is derived — quantity and cost basis are sums over the ledger, average cost, market
         *     value and unrealized P&L are arithmetic on top (ADR-0016, ADR-0020). Nothing here is stored, so
         *     nothing can drift. Reads a :class:`~trading.portfolio.Holding`, whose ``instrument`` is already
         *     ``select_related``, so ``symbol`` and ``name`` cost no extra query.
         */
        Holding: {
            readonly symbol: string;
            readonly name: string;
            /** Format: uuid */
            readonly account_id: string;
            /** Format: decimal */
            readonly quantity: string;
            /** Format: decimal */
            readonly cost_basis: string;
            /** Format: decimal */
            readonly average_cost: string;
            /** Format: decimal */
            readonly last_price: string;
            /** Format: decimal */
            readonly market_value: string;
            /** Format: decimal */
            readonly unrealized_pnl: string;
        };
        /**
         * @description A tradeable symbol and its latest price.
         *
         *     ``drift`` and ``volatility`` are deliberately absent: they are simulation parameters, and
         *     publishing them would tell a client exactly how the "market" it is trading against behaves.
         */
        Instrument: {
            /** Format: uuid */
            readonly id: string;
            readonly symbol: string;
            readonly name: string;
            readonly sector: string;
            readonly currency: string;
            readonly is_active: boolean;
            /** Format: decimal */
            readonly last_price: string;
            /** Format: date-time */
            readonly last_tick_at: string | null;
        };
        /** @description An entry with its lines — the shape a posted transfer returns. */
        JournalEntry: {
            /** Format: uuid */
            readonly id: string;
            readonly description: string;
            readonly idempotency_key: string | null;
            /** Format: date-time */
            readonly created_at: string;
            readonly lines: components["schemas"]["JournalLine"][];
        };
        /**
         * @description One signed leg: ``amount`` is negative leaving the account, positive arriving.
         *
         *     ``quantity`` is null on a money line and the signed share count on a line touching an
         *     instrument account. It was omitted until Week 7, which meant a fill's share movement was
         *     invisible in transaction history — harmless while position accounts were unreachable through
         *     the API, and a silent hole the moment one became reachable.
         */
        JournalLine: {
            readonly id: number;
            /** Format: uuid */
            readonly entry_id: string;
            /** Format: uuid */
            readonly account_id: string;
            /** Format: decimal */
            readonly amount: string;
            /** Format: decimal */
            readonly quantity: string | null;
            readonly currency: string;
            readonly description: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `cash` - Cash account
         *     * `brokerage` - Brokerage
         * @enum {string}
         */
        KindEnum: "cash" | "brokerage";
        Liveness: {
            status: string;
        };
        /**
         * @description Blacklist the presented refresh token and revoke the session behind it.
         *
         *     Stock ``TokenBlacklistView`` only does the first half, which leaves every access token from
         *     that login valid for up to its full lifetime. Revoking the session is what actually logs the
         *     user out.
         */
        Logout: {
            refresh: string;
        };
        /** @description Second step: spend the pre-auth token plus a TOTP code for a real token pair. */
        MFAVerify: {
            mfa_token: string;
            code: string;
        };
        /** @description A bare 6-digit TOTP code, for confirming or disabling a device. */
        MfaCode: {
            code: string;
        };
        MfaEnabled: {
            mfa_enabled: boolean;
        };
        /** @description The one and only time the secret crosses the wire. */
        MfaEnrollResponse: {
            readonly secret: string;
            readonly otpauth_uri: string;
            readonly qr_svg: string;
        };
        /**
         * @description An order and its outcome.
         *
         *     ``entry_id`` is the posting it produced, or null if it never filled.
         */
        Order: {
            /** Format: uuid */
            readonly id: string;
            readonly symbol: string;
            readonly side: components["schemas"]["SideEnum"];
            readonly order_type: components["schemas"]["OrderTypeEnum"];
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: decimal */
            readonly quantity: string;
            /** Format: decimal */
            readonly limit_price: string;
            /** Format: decimal */
            readonly filled_quantity: string;
            /** Format: decimal */
            readonly filled_price: string;
            /** Format: uuid */
            readonly entry_id: string | null;
            readonly idempotency_key: string | null;
            readonly reject_reason: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly resolved_at: string | null;
        };
        /**
         * @description The order request body.
         *
         *     Shape only — whether the instrument is tradeable, whether the account is yours, and whether you
         *     can afford it are the view's and the service's business, exactly as with transfers.
         */
        OrderCreate: {
            symbol: string;
            /** Format: uuid */
            cash_account: string;
            side: components["schemas"]["SideEnum"];
            order_type: components["schemas"]["OrderTypeEnum"];
            /** Format: decimal */
            quantity: string;
            /** Format: decimal */
            limit_price?: string | null;
            idempotency_key?: string | null;
        };
        /**
         * @description * `market` - Market
         *     * `limit` - Limit
         * @enum {string}
         */
        OrderTypeEnum: "market" | "limit";
        PaginatedAccountList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Account"][];
        };
        PaginatedInstrumentList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Instrument"][];
        };
        PaginatedJournalLineList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["JournalLine"][];
        };
        PaginatedPriceTickList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["PriceTick"][];
        };
        PaginatedStatementList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Statement"][];
        };
        /**
         * @description Everything the user owns, valued (ADR-0020).
         *
         *     ``cash`` is asset cash accounts only; ``realized_pnl`` is reported in the sign a human expects,
         *     which is the negation of the income account's ledger balance. Both decisions live in
         *     :mod:`trading.portfolio` — this is the projection, not the arithmetic.
         */
        Portfolio: {
            /** Format: decimal */
            readonly cash: string;
            /** Format: decimal */
            readonly holdings_value: string;
            /** Format: decimal */
            readonly cost_basis: string;
            /** Format: decimal */
            readonly unrealized_pnl: string;
            /** Format: decimal */
            readonly realized_pnl: string;
            /** Format: decimal */
            readonly total_value: string;
            readonly positions: components["schemas"]["Holding"][];
        };
        /** @description One point on a price series — the shape Week 7's chart consumes. */
        PriceTick: {
            /** Format: decimal */
            readonly price: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        Readiness: {
            status: string;
            checks: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Create a user with a validated, hashed password.
         *
         *     ``email`` is required and enforced unique case-insensitively here rather than on the model:
         *     ``django.contrib.auth.models.User.email`` carries no unique constraint, and ADR-0011 rules out
         *     swapping the user model to add one. Registration is the only path that creates users, so this
         *     is where the invariant belongs.
         */
        Register: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Rotate a refresh token, detecting reuse and refusing revoked sessions (ADR-0013). */
        SessionRefresh: {
            refresh: string;
            readonly access: string;
        };
        /**
         * @description * `buy` - Buy
         *     * `sell` - Sell
         * @enum {string}
         */
        SideEnum: "buy" | "sell";
        /**
         * @description One generated statement.
         *
         *     The file itself is deliberately absent: a URL here would be a second way to reach the bytes,
         *     and the download view's ownership check is meant to be the only one (ADR-0021). ``download_url``
         *     is the route, not the storage path.
         */
        Statement: {
            /** Format: uuid */
            readonly id: string;
            readonly kind: components["schemas"]["KindEnum"];
            readonly period: string;
            /** Format: date */
            readonly period_start: string;
            /** Format: date */
            readonly period_end: string;
            /** Format: uuid */
            readonly account_id: string | null;
            /** @description What the statement covers, in one phrase a client can render as a title. */
            readonly symbol_scope: string;
            /** Format: decimal */
            readonly opening_balance: string;
            /** Format: decimal */
            readonly closing_balance: string;
            readonly line_count: number;
            readonly download_url: string;
            /** Format: date-time */
            readonly generated_at: string;
        };
        /**
         * @description * `open` - Open
         *     * `filled` - Filled
         *     * `cancelled` - Cancelled
         *     * `rejected` - Rejected
         * @enum {string}
         */
        StatusEnum: "open" | "filled" | "cancelled" | "rejected";
        /**
         * @description Password step of the login. Returns a token pair, or an MFA challenge (ADR-0012).
         *
         *     The challenge branch is why this returns 200 rather than 401: the credentials *were* correct,
         *     the flow simply is not finished. A 401 would force clients to tell "wrong password" from "need
         *     a code" by parsing an error code, and would trip the generic SPA interceptor that redirects to
         *     login on any 401.
         */
        TokenObtainPairWithMFA: {
            username: string;
            password: string;
        };
        /**
         * @description The transfer request body.
         *
         *     Shape only — ownership, existence, and funds are the view's and the service's business.
         *     ``min_value`` rejects zero and negatives here so the common case fails as a per-field
         *     validation error rather than a domain exception.
         */
        TransferCreate: {
            /** Format: uuid */
            source_account: string;
            /** Format: uuid */
            destination_account: string;
            /** Format: decimal */
            amount: string;
            /** @default Transfer */
            description: string;
            idempotency_key?: string | null;
        };
        /** @description The requesting user's own profile. Never used to expose *another* user. */
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            /** @description True once a TOTP device has been confirmed — enrolled-but-unconfirmed does not count. */
            readonly mfa_enabled: boolean;
            /** Format: date-time */
            readonly date_joined: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccountList"];
                };
            };
        };
    };
    accounts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetail"];
                };
            };
        };
    };
    accounts_transactions_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJournalLineList"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Logout"];
                "application/x-www-form-urlencoded": components["schemas"]["Logout"];
                "multipart/form-data": components["schemas"]["Logout"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_mfa_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCode"];
                "application/x-www-form-urlencoded": components["schemas"]["MfaCode"];
                "multipart/form-data": components["schemas"]["MfaCode"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnabled"];
                };
            };
        };
    };
    auth_mfa_disable_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCode"];
                "application/x-www-form-urlencoded": components["schemas"]["MfaCode"];
                "multipart/form-data": components["schemas"]["MfaCode"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_mfa_enroll_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnrollResponse"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairWithMFA"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairWithMFA"];
                "multipart/form-data": components["schemas"]["TokenObtainPairWithMFA"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPairWithMFA"];
                };
            };
        };
    };
    auth_token_mfa_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MFAVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["MFAVerify"];
                "multipart/form-data": components["schemas"]["MFAVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MFAVerify"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["SessionRefresh"];
                "multipart/form-data": components["schemas"]["SessionRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRefresh"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
        };
    };
    holdings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holding"][];
                };
            };
        };
    };
    instruments_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInstrumentList"];
                };
            };
        };
    };
    instruments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
        };
    };
    instruments_prices_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPriceTickList"];
                };
            };
        };
    };
    orders_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
        };
    };
    orders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderCreate"];
                "multipart/form-data": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description `insufficient_funds` — Not enough funds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description `order_key_conflict` — Key already used. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    orders_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description `order_not_open` — That order is no longer open. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    portfolio_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
    ready_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    statements_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStatementList"];
                };
            };
        };
    };
    statements_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    transfers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["TransferCreate"];
                "multipart/form-data": components["schemas"]["TransferCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
            /** @description `insufficient_funds` — Not enough funds. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description `idempotency_key_conflict` — Key already used. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
