# Generated by Django 5.2.15 on 2026-08-01 04:47

from decimal import Decimal

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_account_instrument_and_more"),
        ("ledger", "0004_journalline_quantity_and_more"),
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "side",
                    models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("market", "Market"), ("limit", "Limit")], max_length=6
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=9,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "limit_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=8, default=Decimal("0E-8"), max_digits=20),
                ),
                (
                    "filled_price",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("reject_reason", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="accounts.account",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="markets.instrument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="order_user_created_idx"),
                    models.Index(
                        condition=models.Q(("status", "open")),
                        fields=["instrument"],
                        name="order_open_instrument_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="order_quantity_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("limit_price__isnull", False), ("order_type", "limit")),
                            models.Q(("limit_price__isnull", True), ("order_type", "market")),
                            _connector="OR",
                        ),
                        name="order_limit_price_iff_limit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("limit_price__isnull", True), ("limit_price__gt", 0), _connector="OR"
                        ),
                        name="order_limit_price_positive",
                    ),
                ],
            },
        ),
    ]
