"""Tradeable instruments and their simulated price history (ADR-0017).

An ``Instrument`` is a symbol you can hold; a ``PriceTick`` is one observation of its price. Prices
here are *synthetic* — generated by the geometric Brownian motion source in :mod:`markets.pricing`
and advanced on a schedule by :func:`markets.tasks.advance_prices` — but nothing downstream knows
that, which is the point: the fill path reads a price, and a live market-data feed swaps in behind
the same interface.

Money and prices are ``NUMERIC(20,4)`` and always ``Decimal`` (ADR-0009). Share *quantities* are
``NUMERIC(20,8)`` and live on the ledger, not here (ADR-0016).
"""

from decimal import Decimal
from typing import Any

import uuid6
from django.db import models


class Instrument(models.Model):
    """A tradeable symbol, plus the parameters its simulated price walks under.

    ``last_price`` and ``last_tick_at`` are a deliberate denormalization of "the newest row in
    ``ticks``". They are a *cache*, not a second source of truth: both are written in the same
    transaction as the tick that produced them, by the single task that produces ticks. The
    alternative — a correlated subquery or a ``DISTINCT ON`` lateral for every instrument list and
    every fill — costs more than a column that has exactly one writer.
    """

    id = models.UUIDField(primary_key=True, default=uuid6.uuid7, editable=False)
    symbol = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100)
    sector = models.CharField(max_length=50, blank=True)
    currency = models.CharField(max_length=3, default="USD")
    # Delisted instruments stay in the table forever: orders and journal lines PROTECT them, and an
    # audit log that references a symbol nobody can look up is not much of an audit log.
    is_active = models.BooleanField(default=True)

    initial_price = models.DecimalField(max_digits=20, decimal_places=4)
    # Annualized geometric Brownian motion parameters: drift is the expected log return per year,
    # volatility its standard deviation. Signed drift is allowed — some things go down.
    drift = models.DecimalField(max_digits=6, decimal_places=4, default=Decimal("0.0800"))
    volatility = models.DecimalField(max_digits=6, decimal_places=4, default=Decimal("0.2500"))

    last_price = models.DecimalField(max_digits=20, decimal_places=4, null=True, blank=True)
    last_tick_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["symbol"]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(initial_price__gt=0),
                name="instrument_initial_price_positive",
            ),
            models.CheckConstraint(
                condition=models.Q(volatility__gte=0),
                name="instrument_volatility_non_negative",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.symbol} ({self.name})"

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Normalize the symbol to upper case so ``unique`` means what a trader thinks it means.

        Postgres unique indexes are case-sensitive, so without this ``aapl`` and ``AAPL`` are two
        instruments — and the second one is unreachable through a URL that upper-cases its lookup.
        """
        self.symbol = self.symbol.upper()
        super().save(*args, **kwargs)

    @property
    def current_price(self) -> Decimal:
        """The price a fill would execute at: the newest tick, or the seed price before any tick."""
        return self.last_price if self.last_price is not None else self.initial_price


class PriceTick(models.Model):
    """One price observation. Append-only by convention; never exposed by ID.

    ``BigAutoField`` PK rather than UUIDv7, following ``JournalLine``: ADR-0005's non-enumerable
    identifiers exist so external references can't be guessed, and nothing outside this table ever
    references a tick. At ~72k rows a day the narrower key is also the cheaper index.
    """

    instrument = models.ForeignKey(
        Instrument,
        on_delete=models.PROTECT,
        related_name="ticks",
    )
    price = models.DecimalField(max_digits=20, decimal_places=4)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(price__gt=0),
                name="price_tick_price_positive",
            ),
        ]
        indexes = [
            # The history endpoint and "newest tick for this instrument" hit exactly this.
            models.Index(fields=["instrument", "-created_at"], name="tick_instrument_created_idx"),
        ]

    def __str__(self) -> str:
        return f"{self.instrument_id} @ {self.price}"
