# Generated by Django 5.2.15 on 2026-07-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0002_entry_balanced_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
