# Generated by Django 5.2.15 on 2026-08-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_instrument_and_more"),
        ("ledger", "0003_journalentry_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="quantity",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__isnull", True),
                    models.Q(("quantity", 0), _negated=True),
                    _connector="OR",
                ),
                name="journal_line_quantity_nonzero",
            ),
        ),
    ]
