# Generated by Django 5.2.15 on 2026-08-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_account_position_account_is_an_asset_and_more"),
        ("ledger", "0006_backfill_entry_fingerprints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="journalline",
            name="journal_line_amount_nonzero",
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), ("quantity__isnull", True), _negated=True),
                name="journal_line_moves_money_or_shares",
            ),
        ),
    ]
