# Generated by Django 5.2.15 on 2026-07-29 01:00

import django.core.serializers.json
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user.registered", "User registered"),
                            ("auth.login_succeeded", "Login succeeded"),
                            ("auth.login_failed", "Login failed"),
                            ("auth.mfa_challenged", "MFA challenge issued"),
                            ("auth.mfa_verified", "MFA code verified"),
                            ("auth.mfa_failed", "MFA code rejected"),
                            ("auth.mfa_enrolled", "MFA device enrolled"),
                            ("auth.mfa_confirmed", "MFA device confirmed"),
                            ("auth.mfa_disabled", "MFA disabled"),
                            ("auth.token_refreshed", "Refresh token rotated"),
                            ("auth.token_reuse_detected", "Refresh token reuse detected"),
                            ("auth.session_revoked", "Session revoked"),
                            ("auth.logout", "Logout"),
                            ("ledger.transfer_posted", "Transfer posted"),
                            ("ledger.transfer_replayed", "Transfer replayed (idempotent)"),
                            ("ledger.transfer_rejected", "Transfer rejected"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=32)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("request_id", models.CharField(blank=True, max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["actor", "-created_at"], name="audit_actor_created_idx"),
                    models.Index(fields=["action", "-created_at"], name="audit_action_created_idx"),
                ],
            },
        ),
    ]
