# Generated by Django 5.2.15 on 2026-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0005_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("user.registered", "User registered"),
                    ("accounts.opened", "Starter accounts opened"),
                    ("auth.login_succeeded", "Login succeeded"),
                    ("auth.login_failed", "Login failed"),
                    ("auth.mfa_challenged", "MFA challenge issued"),
                    ("auth.mfa_verified", "MFA code verified"),
                    ("auth.mfa_failed", "MFA code rejected"),
                    ("auth.mfa_enrolled", "MFA device enrolled"),
                    ("auth.mfa_confirmed", "MFA device confirmed"),
                    ("auth.mfa_disabled", "MFA disabled"),
                    ("auth.token_refreshed", "Refresh token rotated"),
                    ("auth.token_reuse_detected", "Refresh token reuse detected"),
                    ("auth.session_revoked", "Session revoked"),
                    ("auth.logout", "Logout"),
                    ("ledger.transfer_posted", "Transfer posted"),
                    ("ledger.transfer_replayed", "Transfer replayed (idempotent)"),
                    ("ledger.transfer_rejected", "Transfer rejected"),
                    ("ledger.transfer_key_conflict", "Transfer idempotency key conflict"),
                    ("trading.order_placed", "Order placed"),
                    ("trading.order_rested", "Limit order resting"),
                    ("trading.order_filled", "Order filled"),
                    ("trading.order_rejected", "Order rejected"),
                    ("trading.order_cancelled", "Order cancelled"),
                    ("trading.order_key_conflict", "Order idempotency key conflict"),
                    ("ledger.reconciled", "Ledger invariants checked"),
                ],
                max_length=32,
            ),
        ),
    ]
